# Use Dependabot to update the Terraform modules on this example
version: 2
updates:

# DevOps Stack examples
# TODO Check if we can use a wildcard to include all subfolders in the examples folder
- package-ecosystem: "terraform"
  directory: "/" # TODO Add other examples when we are sure everything works
  schedule:
    # Check for updated Terraform modules daily
    interval: "daily"
